# Pre-commit configuration for Frontend ONLY
# Matches exactly what .github/workflows/deploy-frontend.yml does

repos:
  # General file checks (frontend files only)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^frontend/.*
      - id: end-of-file-fixer
        files: ^frontend/.*
      - id: check-yaml
        files: ^frontend/.*\.ya?ml$
      - id: check-json
        files: ^frontend/.*\.json$
      - id: check-merge-conflicts
        files: ^frontend/.*
      - id: check-added-large-files
        args: ['--maxkb=1000']
        files: ^frontend/.*

  # TypeScript/JavaScript checks - EXACTLY matching CI/CD
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.56.0
          - "@typescript-eslint/eslint-plugin@6.21.0"
          - "@typescript-eslint/parser@6.21.0"
          - "eslint-plugin-react@7.33.2"
          - "eslint-plugin-react-hooks@4.6.0"
          - "eslint-plugin-react-refresh@0.4.5"
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^frontend/(dist|node_modules)/.*$
        args: [--write]

  # TypeScript checking - EXACTLY matching CI/CD
  - repo: local
    hooks:
      - id: typescript-check
        name: TypeScript Check
        entry: bash
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        args:
          - -c
          - |
            cd frontend
            npm run check
        pass_filenames: false

  # Frontend tests - EXACTLY matching CI/CD
  - repo: local
    hooks:
      - id: frontend-tests
        name: Frontend Tests
        entry: bash
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx)$
        args:
          - -c
          - |
            cd frontend
            npm run test
            npm run test:integration
        pass_filenames: false

  # Build check - EXACTLY matching CI/CD
  - repo: local
    hooks:
      - id: frontend-build
        name: Frontend Build
        entry: bash
        language: system
        files: ^frontend/.*\.(ts|tsx|js|jsx|json)$
        args:
          - -c
          - |
            cd frontend
            npm run build
        pass_filenames: false

# Configuration
default_language_version:
  node: "18.19.0"

# Only process frontend files
files: ^frontend/.*
exclude: |
  (?x)^(
    frontend/dist/.*|
    frontend/node_modules/.*|
    frontend/.*\.min\.(js|css)|
    frontend/.*\.bundle\.(js|css)
  )$