version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# Note: No local database service needed since we're using Azure SQL Database
# The backend will connect directly to Azure SQL Database using the connection string
      - .env

volumes:
  postgres_data:
