"""Initial migration

Revision ID: 94327365becd
Revises: 753d31e7729a
Create Date: 2025-07-18 13:38:27.886560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94327365becd'
down_revision = '753d31e7729a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
