name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Type checking
      run: npm run check

    - name: Run unit tests
      run: npm run test

    - name: Run integration tests
      run: npm run test:integration

    - name: Install Playwright browsers
      run: npm run test:e2e:install

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Build application
      run: npm run build
      env:
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL || 'https://your-backend.onrender.com/api' }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Vercel
      run: |
        echo "Frontend deployment triggered automatically by Vercel on push to main branch"
        echo "Vercel will build using 'npm run build' in frontend/ directory"
        echo "Environment variables are configured in Vercel dashboard"
